modLoader="javafml"
loaderVersion="[36,)"
license="Academic Free License v3.0"

[[mods]]
modId="vanilla_additions_by_trapp"
version="1.0.0"
displayName="First mod"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="Trapp"
description='''
This mod adds a bunch of semi Vanilla-friendly stuff to make the game more enjoyable.
'''

[[dependencies.vanilla_additions_by_trapp]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"




